package main

import (
	"strings"
	"fmt"
	"bufio"
	"flag"
	"log"
	"os"

	"github.com/majori/gemplate/src/simplify3d"
)

type Arguments struct {
	path string
}

func parseArguments() Arguments {
	flag.Parse()

	return Arguments{
		path: flag.Arg(0),
	}
}

func main() {
	args := parseArguments()
	file, err := os.Open(args.path)
	if err != nil {
		log.Fatal(err)
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	scanner.Scan() // Go to first line 

	var settings map[string]interface{}
	if strings.Contains(scanner.Text(), "G-Code generated by Simplify3D(R)") {
		settings = simplify3d.ParseSettings(scanner)
	}

	fmt.Println(settings)
}
